/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package kr.ac.ssu.ss.tempcollectmanager;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStreamReader;
import javax.swing.ListSelectionModel;
import kr.ac.ssu.ss.collectors.Collector;
import kr.ac.ssu.ss.collectors.CollectorBio;
import kr.ac.ssu.ss.collectors.CollectorVision;
import kr.ac.ssu.ss.collectors.CollectorVoice;

import javax.swing.JLabel;
/**
 *
 * @author lssang
 */
public class MainView extends javax.swing.JFrame {
    
    private UserManager um;
    private DeviceUseManager dm;
    String currnt_id;                                   //current id
    String currnt_name;                                 //current name
    String tmpUserID;
    /**
     * Creates new form MainView
     */
    public MainView() {
        um = new UserManager();
        dm = new DeviceUseManager();
        
        initComponents();
        initUserList();
        initDeviceList();
    }

    /**
     * lssang write
     */
    private void initUserList(){        
        String listData[] = um.getUserList();
        jList_users.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jList_users.setListData(listData);
    }
    
    /**
     * jonghyeok write
     */
    private void initDeviceList() {
        jTextField_CAM1_userID.setText(dm.getVisionDeviceUserID());
        jTextField_MIC1_userID.setText(dm.getVoiceDeviceUserID());
        jTextField_Gear1_userID.setText(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_1));
        jTextField_Gear2_userID.setText(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_2));
        jTextField_Gear3_userID.setText(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_3));
        
        // Device and User Mapping info setting
        if(um.containId(dm.getVisionDeviceUserID())) {
            um.getUser(dm.getVoiceDeviceUserID()).setVision_d_id(Constants.VISION_DEVICE_NAME); 
        } if(um.containId(dm.getVoiceDeviceUserID())) {
            um.getUser(dm.getVoiceDeviceUserID()).setVoice_d_id(Constants.VOICE_DEVICE_NAME); 
        } if(um.containId(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_1))) {
            um.getUser(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_1)).setBio_d_id(Constants.BIO_DEVICE_NAME_1); 
        } if(um.containId(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_2))) {
            um.getUser(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_2)).setBio_d_id(Constants.BIO_DEVICE_NAME_2); 
        } if(um.containId(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_3))) {
            um.getUser(dm.getBioDeviceUserID(Constants.BIO_DEVICE_NAME_3)).setBio_d_id(Constants.BIO_DEVICE_NAME_3); 
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabelTitle = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_searchUserId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_searchUserName = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deviceId_vision = new javax.swing.JLabel();
        status_vision = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton_on_vision = new javax.swing.JButton();
        jButton_off_vision = new javax.swing.JButton();
        deviceId_bio = new javax.swing.JLabel();
        status_bio = new javax.swing.JLabel();
        jButton_on_bio = new javax.swing.JButton();
        jButton_off_bio = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        deviceId_voice = new javax.swing.JLabel();
        jButton_on_voice = new javax.swing.JButton();
        jButton_off_voice = new javax.swing.JButton();
        status_voice = new javax.swing.JLabel();
        jLabe_searchResult = new javax.swing.JLabel();
        jPanelSystem = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel_CAM1_status = new javax.swing.JLabel();
        jTextField_CAM1_userID = new javax.swing.JTextField();
        jToggleButton_CAM1_Edit = new javax.swing.JToggleButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel_gear1_status = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel_gear2_status = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel_gear3_status = new javax.swing.JLabel();
        jTextField_Gear1_userID = new javax.swing.JTextField();
        jTextField_Gear2_userID = new javax.swing.JTextField();
        jTextField_Gear3_userID = new javax.swing.JTextField();
        jToggleButton_Gear1_Edit = new javax.swing.JToggleButton();
        jToggleButton_Gear2_Edit = new javax.swing.JToggleButton();
        jToggleButton_Gear3_Edit = new javax.swing.JToggleButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel_MIC1_status = new javax.swing.JLabel();
        jTextField_MIC1_userID = new javax.swing.JTextField();
        jToggleButton_MIC1_Edit = new javax.swing.JToggleButton();
        jPanelUser = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_addUserId = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_addUserName = new javax.swing.JTextField();
        jButton_addUser = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList_users = new javax.swing.JList();
        jLabe_addResult = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setText("Data Collect Manager");

        jLabel1.setText("UserID");

        jTextField_searchUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchUserIdActionPerformed(evt);
            }
        });

        jLabel2.setText("Name");

        jButton_search.setText("Search");
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jLabel3.setText("Type");

        jLabel4.setText("DeviceId");

        jLabel5.setText("Control");

        jLabel6.setText("Status");

        jLabel7.setText("Vision");

        deviceId_vision.setText("none");

        status_vision.setForeground(new java.awt.Color(255, 0, 0));
        status_vision.setText("OFF");

        jLabel10.setText("Bio");

        jButton_on_vision.setText("ON");
        jButton_on_vision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_visionActionPerformed(evt);
            }
        });

        jButton_off_vision.setText("OFF");
        jButton_off_vision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_off_visionActionPerformed(evt);
            }
        });

        deviceId_bio.setText("none");

        status_bio.setForeground(new java.awt.Color(255, 0, 0));
        status_bio.setText("OFF");

        jButton_on_bio.setText("ON");
        jButton_on_bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_bioActionPerformed(evt);
            }
        });

        jButton_off_bio.setText("OFF");
        jButton_off_bio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_off_bioActionPerformed(evt);
            }
        });

        jLabel13.setText("Voice");

        deviceId_voice.setText("none");

        jButton_on_voice.setText("ON");
        jButton_on_voice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_on_voiceActionPerformed(evt);
            }
        });

        jButton_off_voice.setText("OFF");
        jButton_off_voice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_off_voiceActionPerformed(evt);
            }
        });

        status_voice.setForeground(new java.awt.Color(255, 0, 0));
        status_voice.setText("OFF");

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4))
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(deviceId_voice, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deviceId_vision, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(deviceId_bio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                                        .addComponent(jButton_on_voice)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_off_voice))
                                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                                        .addComponent(jButton_on_bio)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_off_bio))
                                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                                        .addComponent(jButton_on_vision)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_off_vision)))
                                .addGap(127, 127, 127)
                                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(status_bio)
                                    .addComponent(status_vision)
                                    .addComponent(status_voice))
                                .addGap(0, 98, Short.MAX_VALUE))
                            .addGroup(jPanelHomeLayout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(86, 86, 86))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_searchUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField_searchUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton_search))
                    .addGroup(jPanelHomeLayout.createSequentialGroup()
                        .addComponent(jLabe_searchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField_searchUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_searchUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_search))
                .addGap(3, 3, 3)
                .addComponent(jLabe_searchResult, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(deviceId_vision, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_vision)
                    .addComponent(jButton_on_vision)
                    .addComponent(jButton_off_vision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(deviceId_bio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(status_bio)
                    .addComponent(jButton_on_bio)
                    .addComponent(jButton_off_bio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(deviceId_voice, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_on_voice)
                    .addComponent(jButton_off_voice)
                    .addComponent(status_voice))
                .addContainerGap(241, Short.MAX_VALUE))
        );

        deviceId_voice.getAccessibleContext().setAccessibleName("60");

        jTabbedPane1.addTab("Home", jPanelHome);

        jLabel8.setText("Vision");

        jLabel9.setText("Bio");

        jLabel11.setText("Voice");

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel17.setText("Device ID");

        jLabel18.setText("Status");

        jLabel19.setText("User ID");

        jLabel20.setText("CAM1");

        jLabel_CAM1_status.setText("Stopped");

        jTextField_CAM1_userID.setEditable(false);

        jToggleButton_CAM1_Edit.setText("Edit");
        jToggleButton_CAM1_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_CAM1_EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20))
                .addGap(65, 65, 65)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel_CAM1_status, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jTextField_CAM1_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jToggleButton_CAM1_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel_CAM1_status)
                    .addComponent(jTextField_CAM1_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_CAM1_Edit))
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setToolTipText("");

        jLabel23.setText("Device ID");

        jLabel24.setText("Status");

        jLabel25.setText("User ID");

        jLabel26.setText("Gear1");

        jLabel_gear1_status.setText("Stopped");

        jLabel29.setText("Gear2");

        jLabel_gear2_status.setText("Stopped");

        jLabel32.setText("Gear3");

        jLabel_gear3_status.setText("Stopped");

        jTextField_Gear1_userID.setEditable(false);
        jTextField_Gear1_userID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Gear1_userIDActionPerformed(evt);
            }
        });

        jTextField_Gear2_userID.setEditable(false);
        jTextField_Gear2_userID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Gear2_userIDActionPerformed(evt);
            }
        });

        jTextField_Gear3_userID.setEditable(false);
        jTextField_Gear3_userID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_Gear3_userIDActionPerformed(evt);
            }
        });

        jToggleButton_Gear1_Edit.setText("Edit");
        jToggleButton_Gear1_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Gear1_EditActionPerformed(evt);
            }
        });

        jToggleButton_Gear2_Edit.setText("Edit");
        jToggleButton_Gear2_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Gear2_EditActionPerformed(evt);
            }
        });

        jToggleButton_Gear3_Edit.setText("Edit");
        jToggleButton_Gear3_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_Gear3_EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel29)
                    .addComponent(jLabel32))
                .addGap(65, 65, 65)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_gear1_status, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_gear2_status)
                    .addComponent(jLabel_gear3_status, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Gear2_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Gear1_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Gear3_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToggleButton_Gear1_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_Gear2_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleButton_Gear3_Edit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel_gear1_status)
                    .addComponent(jTextField_Gear1_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_Gear1_Edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jLabel_gear2_status)
                    .addComponent(jTextField_Gear2_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_Gear2_Edit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel32)
                        .addComponent(jLabel_gear3_status))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_Gear3_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jToggleButton_Gear3_Edit)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jLabel_gear2_status.getAccessibleContext().setAccessibleName("60");

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel35.setText("Device ID");

        jLabel36.setText("Status");

        jLabel37.setText("User ID");

        jLabel38.setText("MIC1");

        jLabel_MIC1_status.setText("Stopped");

        jTextField_MIC1_userID.setEditable(false);

        jToggleButton_MIC1_Edit.setText("Edit");
        jToggleButton_MIC1_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton_MIC1_EditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38))
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel_MIC1_status, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_MIC1_userID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(jToggleButton_MIC1_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(99, 99, 99)
                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(jLabel_MIC1_status)
                    .addComponent(jTextField_MIC1_userID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButton_MIC1_Edit))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelSystemLayout = new javax.swing.GroupLayout(jPanelSystem);
        jPanelSystem.setLayout(jPanelSystemLayout);
        jPanelSystemLayout.setHorizontalGroup(
            jPanelSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSystemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelSystemLayout.createSequentialGroup()
                        .addGroup(jPanelSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelSystemLayout.setVerticalGroup(
            jPanelSystemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSystemLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8)
                .addGap(2, 2, 2)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jTabbedPane1.addTab("System", jPanelSystem);

        jLabel14.setText("User ID");

        jTextField_addUserId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_addUserIdActionPerformed(evt);
            }
        });

        jLabel15.setText("Name");

        jButton_addUser.setText("ADD");
        jButton_addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addUserActionPerformed(evt);
            }
        });

        jLabel16.setText("User List");

        jList_users.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(jList_users);

        javax.swing.GroupLayout jPanelUserLayout = new javax.swing.GroupLayout(jPanelUser);
        jPanelUser.setLayout(jPanelUserLayout);
        jPanelUserLayout.setHorizontalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUserLayout.createSequentialGroup()
                        .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5)
                            .addGroup(jPanelUserLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_addUserId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField_addUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                .addComponent(jButton_addUser, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanelUserLayout.createSequentialGroup()
                        .addComponent(jLabe_addResult, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelUserLayout.setVerticalGroup(
            jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUserLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_addUserId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_addUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_addUser))
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabe_addResult, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(174, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", jPanelUser);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_on_bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_bioActionPerformed
        // TODO add your handling code here:
        pushOnOff(Constants.BIO, Constants.ON);        
    }//GEN-LAST:event_jButton_on_bioActionPerformed

    private void jButton_on_visionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_visionActionPerformed
        // TODO add your handling code here:
        pushOnOff(Constants.VISION, Constants.ON);  
    }//GEN-LAST:event_jButton_on_visionActionPerformed

    private void jButton_addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_addUserActionPerformed
        // TODO add your handling code here:
        String id = jTextField_addUserId.getText();
        String name = jTextField_addUserName.getText();
                
        int res = um.addUser(id, name);
        if(res == Constants.DONE){
            jLabe_addResult.setText("DONE");
            initUserList();
        }else if(res == Constants.ALREADY_EXIST){
            jLabe_addResult.setText("This id aleady exists.");
        }
    }//GEN-LAST:event_jButton_addUserActionPerformed

    private void jTextField_addUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_addUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_addUserIdActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        // TODO add your handling code here:
        String id = jTextField_searchUserId.getText();      //input id
        String name = jTextField_searchUserName.getText();  //input name
        
            
        if(um.containId(id)){
            currnt_id = id;                                  
            currnt_name = um.getNameById(id);                 
            jTextField_searchUserName.setText(currnt_name);
            jLabe_searchResult.setText("Search by id... currunt user : "+currnt_name+"("+currnt_id+")");
            setHomeInfo(currnt_id);            
        }else if(um.containName(name)){
            currnt_name = name;
            currnt_id = um.getIdByName(name);
            jTextField_searchUserId.setText(currnt_id);
            jLabe_searchResult.setText("Search by name...currunt user : "+currnt_name+"("+currnt_id+")");
            setHomeInfo(currnt_id);
        }else{
            jLabe_searchResult.setText("User not found.");
        }
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_on_voiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_on_voiceActionPerformed
        // TODO add your handling code here:
        pushOnOff(Constants.VOICE, Constants.ON);   
    }//GEN-LAST:event_jButton_on_voiceActionPerformed

    private void jButton_off_visionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_off_visionActionPerformed
        // TODO add your handling code here:
        pushOnOff(Constants.VISION, Constants.OFF);
    }//GEN-LAST:event_jButton_off_visionActionPerformed

    private void jButton_off_bioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_off_bioActionPerformed
        // TODO add your handling code here:
        pushOnOff(Constants.BIO, Constants.OFF);
    }//GEN-LAST:event_jButton_off_bioActionPerformed

    private void jButton_off_voiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_off_voiceActionPerformed
        // TODO add your handling code here:
        pushOnOff(Constants.VOICE, Constants.OFF);
    }//GEN-LAST:event_jButton_off_voiceActionPerformed

    private void jTextField_Gear1_userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Gear1_userIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Gear1_userIDActionPerformed

    private void jTextField_Gear2_userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Gear2_userIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Gear2_userIDActionPerformed

    private void jTextField_Gear3_userIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_Gear3_userIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_Gear3_userIDActionPerformed

    private void jTextField_searchUserIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchUserIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchUserIdActionPerformed

    private void jToggleButton_CAM1_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_CAM1_EditActionPerformed
        if(jToggleButton_CAM1_Edit.isSelected()) {
            tmpUserID = jTextField_CAM1_userID.getText();
            jTextField_CAM1_userID.setEditable(true);
            jTextField_CAM1_userID.setBackground(Color.pink);
        } else {
            jTextField_CAM1_userID.setEditable(false);
            jTextField_CAM1_userID.setBackground(Color.white);
            String inputUserID = jTextField_CAM1_userID.getText();
            
            if(um.containId(inputUserID)) {
                dm.setVisionDeviceUserID(inputUserID);
                if(!tmpUserID.equals("none")) {
                    um.getUser(tmpUserID).setVision_d_id("none");
                }
                um.getUser(inputUserID).setVision_d_id(Constants.VISION_DEVICE_NAME);                
            } else {
                jTextField_CAM1_userID.setText(tmpUserID);
            }
        }
    }//GEN-LAST:event_jToggleButton_CAM1_EditActionPerformed

    private void jToggleButton_Gear1_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Gear1_EditActionPerformed
        if(jToggleButton_Gear1_Edit.isSelected()) {
            tmpUserID = jTextField_Gear1_userID.getText();
            jTextField_Gear1_userID.setEditable(true);
            jTextField_Gear1_userID.setBackground(Color.pink);
        } else {
            jTextField_Gear1_userID.setEditable(false);
            jTextField_Gear1_userID.setBackground(Color.white);
            String inputUserID = jTextField_Gear1_userID.getText();
            
            if(um.containId(inputUserID)) {
                dm.setBioDeviceUserID(Constants.BIO_DEVICE_NAME_1, inputUserID);
                if(!tmpUserID.equals("none")) {
                    um.getUser(tmpUserID).setBio_d_id("none");
                }
                um.getUser(inputUserID).setBio_d_id(Constants.BIO_DEVICE_NAME_1);                
            } else {
                jTextField_Gear1_userID.setText(tmpUserID);
            }
        }
    }//GEN-LAST:event_jToggleButton_Gear1_EditActionPerformed

    private void jToggleButton_Gear2_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Gear2_EditActionPerformed
        if(jToggleButton_Gear2_Edit.isSelected()) {
            tmpUserID = jTextField_Gear2_userID.getText();
            jTextField_Gear2_userID.setEditable(true);
            jTextField_Gear2_userID.setBackground(Color.pink);
        } else {
            jTextField_Gear2_userID.setEditable(false);
            jTextField_Gear2_userID.setBackground(Color.white);
            String inputUserID = jTextField_Gear2_userID.getText();
            
            if(um.containId(inputUserID)) {
                dm.setBioDeviceUserID(Constants.BIO_DEVICE_NAME_2, inputUserID);
                if(!tmpUserID.equals("none")) {
                    um.getUser(tmpUserID).setBio_d_id("none");
                }
                um.getUser(inputUserID).setBio_d_id(Constants.BIO_DEVICE_NAME_2);                
                
            } else {
                jTextField_Gear2_userID.setText(tmpUserID);
            }
        }
    }//GEN-LAST:event_jToggleButton_Gear2_EditActionPerformed

    private void jToggleButton_Gear3_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_Gear3_EditActionPerformed
        if(jToggleButton_Gear3_Edit.isSelected()) {
            tmpUserID = jTextField_Gear3_userID.getText();
            jTextField_Gear3_userID.setEditable(true);
            jTextField_Gear3_userID.setBackground(Color.pink);
        } else {
            jTextField_Gear3_userID.setEditable(false);
            jTextField_Gear3_userID.setBackground(Color.white);
            String inputUserID = jTextField_Gear3_userID.getText();
            
            if(um.containId(inputUserID)) {
                dm.setBioDeviceUserID(Constants.BIO_DEVICE_NAME_3, inputUserID);
                if(!tmpUserID.equals("none")) {
                    um.getUser(tmpUserID).setBio_d_id("none");
                }
                um.getUser(inputUserID).setBio_d_id(Constants.BIO_DEVICE_NAME_3);                
                
            } else {
                jTextField_Gear3_userID.setText(tmpUserID);
            }
        }
    }//GEN-LAST:event_jToggleButton_Gear3_EditActionPerformed

    private void jToggleButton_MIC1_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton_MIC1_EditActionPerformed
        if(jToggleButton_MIC1_Edit.isSelected()) {
            tmpUserID = jTextField_MIC1_userID.getText();
            jTextField_MIC1_userID.setEditable(true);
            jTextField_MIC1_userID.setBackground(Color.pink);
        } else {
            jTextField_MIC1_userID.setEditable(false);
            jTextField_MIC1_userID.setBackground(Color.white);
            String inputUserID = jTextField_MIC1_userID.getText();
            
            if(um.containId(inputUserID)) {
                dm.setVoiceDeviceUserID(inputUserID);
                if(!tmpUserID.equals("none")) {
                    um.getUser(tmpUserID).setVoice_d_id("none");
                }
                um.getUser(inputUserID).setVoice_d_id(Constants.VOICE_DEVICE_NAME);              
            } else {
                jTextField_MIC1_userID.setText(tmpUserID);
            }
        }
    }//GEN-LAST:event_jToggleButton_MIC1_EditActionPerformed
    
    private void setStatus(int collectorType, String deviceId, int btnType){
        
        Collector collector = null;
        String msg = "";
        Color color = null;
        if(btnType == Constants.ON){
            msg = "Running";
            color = new Color(0, 255, 0);
        }else if(btnType == Constants.OFF){
            msg = "Stopped";
            color = new Color(255, 0, 0);
        }
        
        switch(collectorType){
            case Constants.VISION:
                status_vision.setText(msg);
                status_vision.setForeground(color);
                jLabel_CAM1_status.setText(msg);
                jLabel_CAM1_status.setForeground(color);
                dm.setVisionDeviceStatus(btnType); break;
            case Constants.BIO:
                status_bio.setText(msg);
                status_bio.setForeground(color);
                if(deviceId == Constants.BIO_DEVICE_NAME_1) {
                    jLabel_gear1_status.setText(msg);
                    jLabel_gear1_status.setForeground(color);
                } else if(deviceId == Constants.BIO_DEVICE_NAME_2) {
                    jLabel_gear2_status.setText(msg);
                    jLabel_gear2_status.setForeground(color);
                } else if(deviceId == Constants.BIO_DEVICE_NAME_3) {
                    jLabel_gear3_status.setText(msg);
                    jLabel_gear3_status.setForeground(color);
                }
                
                dm.setBioDeviceStatus(deviceId, btnType); break;
            case Constants.VOICE:
                status_voice.setText(msg);
                status_voice.setForeground(color);
                jLabel_MIC1_status.setText(msg);
                jLabel_MIC1_status.setForeground(color);                
                dm.setVoiceDeviceStatus(btnType); break;            
           default:
        }
    }
    
    private void pushOnOff(int collectorType, int btnType) {
        Collector collector = null;
        String deviceId = "";
        
        switch(collectorType){
            case Constants.VISION: 
                deviceId = deviceId_vision.getText();
                collector = new CollectorVision(); break;
            case Constants.BIO: 
                deviceId = deviceId_bio.getText();
                collector = new CollectorBio(); break;
            case Constants.VOICE: 
                deviceId = deviceId_voice.getText();
                collector = new CollectorVoice(); break;              
           default:
        }
        
        int res = Constants.INIT_RESULT;
        
        switch(btnType){
            case Constants.ON :  res= collector.startCollecting(); break;
            case Constants.OFF :  res= collector.stopCollecting(); break;
        }
               
        if( res == Constants.DONE){
            setStatus(collectorType, deviceId, btnType);
        }else{
            //error!
        }       
    }
            
    private void setHomeInfo(String userId){
       deviceId_vision.setText(um.getUser(userId).getVision_d_id());
       deviceId_bio.setText(um.getUser(userId).getBio_d_id());
       deviceId_voice.setText(um.getUser(userId).getVoice_d_id());
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deviceId_bio;
    private javax.swing.JLabel deviceId_vision;
    private javax.swing.JLabel deviceId_voice;
    private javax.swing.JButton jButton_addUser;
    private javax.swing.JButton jButton_off_bio;
    private javax.swing.JButton jButton_off_vision;
    private javax.swing.JButton jButton_off_voice;
    private javax.swing.JButton jButton_on_bio;
    private javax.swing.JButton jButton_on_vision;
    private javax.swing.JButton jButton_on_voice;
    private javax.swing.JButton jButton_search;
    private javax.swing.JLabel jLabe_addResult;
    private javax.swing.JLabel jLabe_searchResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabel_CAM1_status;
    private javax.swing.JLabel jLabel_MIC1_status;
    private javax.swing.JLabel jLabel_gear1_status;
    private javax.swing.JLabel jLabel_gear2_status;
    private javax.swing.JLabel jLabel_gear3_status;
    private javax.swing.JList jList_users;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelHome;
    private javax.swing.JPanel jPanelSystem;
    private javax.swing.JPanel jPanelUser;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_CAM1_userID;
    private javax.swing.JTextField jTextField_Gear1_userID;
    private javax.swing.JTextField jTextField_Gear2_userID;
    private javax.swing.JTextField jTextField_Gear3_userID;
    private javax.swing.JTextField jTextField_MIC1_userID;
    private javax.swing.JTextField jTextField_addUserId;
    private javax.swing.JTextField jTextField_addUserName;
    private javax.swing.JTextField jTextField_searchUserId;
    private javax.swing.JTextField jTextField_searchUserName;
    private javax.swing.JToggleButton jToggleButton_CAM1_Edit;
    private javax.swing.JToggleButton jToggleButton_Gear1_Edit;
    private javax.swing.JToggleButton jToggleButton_Gear2_Edit;
    private javax.swing.JToggleButton jToggleButton_Gear3_Edit;
    private javax.swing.JToggleButton jToggleButton_MIC1_Edit;
    private javax.swing.JLabel status_bio;
    private javax.swing.JLabel status_vision;
    private javax.swing.JLabel status_voice;
    // End of variables declaration//GEN-END:variables
}
